server:
  port: 7700
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xw_zipkin?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: xw-zipkin-service
zipkin:
  storage:
    #type: mysql
    StorageComponent: mysql
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
